config-version: 1
config:
  bitcoinRpcHost:
    name: Bitcoin RPC Host
    description: Hostname of your Bitcoin Core node.
    type: string
    required: true
  bitcoinRpcPort:
    name: Bitcoin RPC Port
    description: Port of your Bitcoin Core node.
    type: integer
    default: 8332
  bitcoinRpcUser:
    name: Bitcoin RPC Username
    description: RPC username for your Bitcoin Core node.
    type: string
    required: true
  bitcoinRpcPassword:
    name: Bitcoin RPC Password
    description: RPC password for your Bitcoin Core node.
    type: string
    required: true
